### ISSUE TITLE
[Request] sensor for HA only with waiting_time value

### ISSUE THREAD

**Issue by tebra-jl** [Emilv2/stib_mivb#4]
I want to push "waiting_time" of 2 next passages to my Esphome e-ink screen.
For that I need to build one sensor with "waiting_time" value for the first passage et another sensor with "waiting_time" value for the second passage.
I try with this in my configuration.yaml

```
sensor:
  - platform: template
    sensors:
      stib_line_5_delta_hdebroux_next:
        unit_of_measurement: 'min'
        friendly_name: 'Time Line 5 Delta direction H-Debroux'
        value_template: "{{ states.sensor.delta_line_5.field.waiting_time }}"
```
Any help ?

**Comment by Emilv2** [comment]
This should do it:
```
sensor:
  - platform: template
    sensors:

      stib_line_5_delta_hdebroux_next:
        unit_of_measurement: 'min'
        friendly_name: 'Time Line 5 Delta direction H-Debroux'
        value_template: "{{ state_attr('sensor.delta_line_5',  'next_passages')[0]['waiting_time'] }}"
```
Increase `0` for the trains after the next.
