### ISSUE TITLE
same stop 2 directions: same sensor name

### ISSUE THREAD

**Issue by tebra-jl** [Emilv2/stib_mivb#5]
I have this in my configuration.yaml
```
    stops:
      - stop_id: 8231
        line_numbers:
          - 5
      - stop_id: 8232
        line_numbers:
          - 5
```
This generate 2 sensors "sensor.delta_line_5" and "sensor.delta_line_5_2". One for each directions.
BUT after a restart of HA their labels are switching.
